image: python:3.7-stretch

pages:
  script:
  - pip install -r requirements.txt
  - pip install sphinx numpydoc sphinx_rtd_theme sphinx-nbexamples pandoc
  - cd src
  - python test.py
  - cd ..
  - ls
  - cd doc
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  - ls public
  artifacts:
    paths:
    - public
  only:
  - master
