image: python:3.7-stretch

test:
  script:
  - pip install -r requirements.txt
  - cd src
  - python test.py

pages:
  script:
  - pip install -r requirements.txt
  - apt-get update
  - apt-get install --assume-yes pandoc
  - pip install sphinx numpydoc sphinx_rtd_theme sphinx-nbexamples
  - cd doc
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  - ls public
  artifacts:
    paths:
    - public
  only:
  - master
